### ISSUE TITLE
failed attempt on Ancient Mana Crystal

### ISSUE THREAD

**Issue by spiralofhope** [HgAlexx/Buffet#10]
**Describe the bug**

I get "... failed attempt on: [Ancient Mana Crystal](https://www.wowhead.com/item=139786/ancient-mana-crystal)

**To Reproduce**

Every login or reloadui.

**Related Item**

https://www.wowhead.com/item=139786/ancient-mana-crysta

**Language**

en

**Comment by HgAlexx** [comment]
see #11
