### ISSUE TITLE
failed attempt on Green Firework

### ISSUE THREAD

**Issue by spiralofhope** [HgAlexx/Buffet#11]
**Describe the bug**

4 failed attempt on: [Green Firework](https://www.wowhead.com/item=9313/green-firework)

**To Reproduce**

every login or reloadui

**Related Item**

https://www.wowhead.com/item=9313/green-firework

**Language**

en

**Comment by HgAlexx** [comment]
Hello,

The source from github has debug enable by default, which is turned off in builds.
You can disable debug mode in Utility.lua, clear the content of function Utility.Debug(...)

**Comment by HgAlexx** [comment]
Debug is now off by default with a flag near the top of Utility.lua

**Comment by spiralofhope** [comment]
It's strange..

This:

https://github.com/HgAlexx/Buffet/blob/c11461f62c3a7a8f2e7f998031fc92b1a4d35fe0/Utility.lua#L45-L47

Does not appear to honor this:

https://github.com/HgAlexx/Buffet/blob/c11461f62c3a7a8f2e7f998031fc92b1a4d35fe0/Utility.lua#L13

I did end up emptying `function Utility.Debug(...)` to stop that functionality.

**Comment by HgAlexx** [comment]
Strange indeed, I'll retest that later today.

**Comment by HgAlexx** [comment]
Fixed.
Note to self: do not fix issue when tired ;)
I was using the same name for the variable and for the function ...
