### ISSUE TITLE
Darkmoon Daggermaw does not show up in Food Only macro

### ISSUE THREAD

**Issue by vttale** [HgAlexx/Buffet#13]
**Describe the bug**
I've dragged the Food Only macro to my bar and it does not change from the Heathstone default even though I have Darkmoon Daggermaw in my bag.   Debug info for the item is:
Buffet: Item [Darkmoon Daggermaw]:
Buffet: - Is health: Yes
Buffet: - Is mana: Yes
Buffet: - Is well fed: No
Buffet: - Is conjured: No
Buffet: - Is percent: Yes
Buffet: - Is potion: No
Buffet: - Is bandage: No
Buffet: - Is over time: Yes
Buffet: - health value: 5% (1003 hp) per second over 20 second for a total of 100% (20060 hp)
Buffet: - mana value: 5% (5 mp) per second over 20 second for a total of 100% (100 mp)
Buffet: - itemClassId: 7
Buffet: - itemSubClassId: 8

**To Reproduce**
Have the Darkmoon Daggermaw in your bag, make a Buffet macro and see whether it shows up

**Related Item**
https://www.wowhead.com/item=124669/darkmoon-daggermaw

**Language**
enUS

**Comment by HgAlexx** [comment]
God I love a proper bug report :D
Should be fix in the new release!

**Comment by HgAlexx** [comment]
For some reason, the release is still under review..
https://www.curseforge.com/wow/addons/buffet/files
