### ISSUE TITLE
Buffet does not recognize Conjured Mana Bun

### ISSUE THREAD

**Issue by lyndametref** [HgAlexx/Buffet#15]
**Describe the bug**
Buffet does not recognize Conjured Mana Bun (and other food)

**To Reproduce**
Have only conjured mana in your bag on the hearthstone is showing in the macro (even after /buffer clear and /buffer scan)
This also happen with other food/ drink.
release 9.0.2.66

**Related Item**
Please provide a WowHead link to the related item if applicable:
https://www.wowhead.com/item=113509/conjured-mana-bun

**Language**
Please specify the language of your wow client:
English

**Comment by HgAlexx** [comment]
This is a old bug making a come back, I'll push a fix in the next few hours ;)
This is mainly due to Blizzard changing some items tooltip format.

**Comment by lyndametref** [comment]
Now working properly! /thanks
