### ISSUE TITLE
Macro that includes Well Fed items

### ISSUE THREAD

**Issue by OverlordQ** [HgAlexx/Buffet#17]
Often when leveling, that's the only food you have because that's what the vendors sell. So instead of using the items that are appropriate for my level, it'll only use the level 5 piece of meat that heals for 200 hp. 

EG: Doing Chromie Time MoP, and instead of using [Pounded Rice Cakes](https://www.wowhead.com/item=81400/pounded-rice-cake) I got from the vendor, it wants to only use [Mutton Chop](https://www.wowhead.com/item=3770/mutton-chop)

**Comment by HgAlexx** [comment]
Hello,

In the last beta I introduced Custom Macros and made "well fed" items available to them.

Following these changes, I should be able to easily add an options to include any "well fed" items in normal macros.

I'll see if I can add that sometime next week.

**Comment by HgAlexx** [comment]
Available in last beta version, if any items is not properly detected, please provide me the item Id and the exact tooltip text if possible (wowhead description is not always accurate).
