### ISSUE TITLE
"Third Wind" Potion selected for Consumables even when not in a usable battleground

### ISSUE THREAD

**Issue by vttale** [HgAlexx/Buffet#18]
**The bug:**
The "Third Wind" Potion will always show up in the Consumables macro even when it is not in a usable area.  You can use them in regular battlegrounds and brawls, but not in any other PvE or PvP setting (arenas, rated BGs, open world warmode, etc).  

Buffet: Item ["Third Wind" Potion]:
Buffet: - Is health: Yes
Buffet: - Is mana: No
Buffet: - Is well fed: No
Buffet: - Is conjured: No
Buffet: - Is percent: Yes
Buffet: - Is potion: Yes
Buffet: - Is bandage: No
Buffet: - Is over time: No
Buffet: - Is restricted:  No
Buffet: - health value: 50% (20550 hp)
Buffet: - mana value: 0% (0 mp)
Buffet: - itemClassId: 0
Buffet: - itemSubClassId: 1

**To Reproduce**
Have the Third Wind Potion in your bag but not a warlock healthstone because the latter is thankfully selected preferentially.  I'm not sure what other items might take priority over it, but I know that when I have Third Wind and regular health potions in my bag, the Third Wind one is the one that is selected even when not usable.

**Related Item**
https://www.wowhead.com/item=138486/third-wind-potion

**Language**
enUS

**Comment by HgAlexx** [comment]
Hello,

I can restrict it to all BGs but I'm not sure about rated ones. Also, what do you mean by brawls?

Can you try something ?

Edit the following file: "Buffet/Retail/ConstRetail.lua"

Go to the end and add this before the last "}":
```
    [138486] = { -- Third wind potion
        inInstanceTypes = { "pvp" },
    },
```

This will restrict the potion to all BGs, excluding arena, no idea regarding rated.

If this works, I'll do a release with it.

**Comment by vttale** [comment]
Brawls are basically just unrated BGs that have special rulesets from their regular versions.  AFAIK you can use anything in them that you can use in a regular unrated BG, so no real reason to distinguish them.

Rated vs unrated matters a lot though.  There's a ton of items you can't use in rated BGs or arenas.  Looks like "C_PvP.IsRatedBattleground() or C_PvP.IsArena()" would be an easy way to deal with it.

**Comment by HgAlexx** [comment]
Thanks, I'll have a look at that ;)

**Comment by HgAlexx** [comment]
Does this look ok to you ?
`pvp = { bg = true, arena = false, brawl = true, ratedBg = false, ratedArena = false  }`

**Comment by HgAlexx** [comment]
I built a new Beta, can you try it ?

https://www.curseforge.com/wow/addons/buffet/files/3209186

**Comment by vttale** [comment]
Hmm, just jumped into a brawl to try with your beta.  C_PvP.IsBattleground() is true, C_PcP.IsInBrawl() is true, and C_PvP.IsRatedBattleground() is false.     The potion stack that is in my bag should show for Consumables, but instead it is showing Spiritual Healing Potion.

On the plus side, the Third Wind potion is no longer taking unusable precedence in PvE.

**Comment by HgAlexx** [comment]
Does 50% of your health is greater than what Spiritual Healing Potion give you ?
Maybe it's just because of the return health of each potion.

**Comment by HgAlexx** [comment]
you can use /buffet debug [item link]
to check each item for their health values

**Comment by HgAlexx** [comment]
Nevermind, I know the issue, it's my bad :)

Change ConstRetail to match this:
```
    [138486] = { -- Third wind potion
        {
            matchMode = "any",
            pvp = { bg = true, brawl = true }
        },
    },

```

**Comment by HgAlexx** [comment]
Should be fix in last beta (v73)
