### ISSUE TITLE
Buffet Won't Detect Seafoam Coconut Water

### ISSUE THREAD

**Issue by steffmaister** [HgAlexx/Buffet#2]
Buffet Won't Detect Seafoam Coconut Water! Is there a fix?

**Comment by HgAlexx** [comment]
Hi,
Is this the right item ? https://www.wowhead.com/item=163784/seafoam-coconut-water
Which language do you use, english ?

**Comment by steffmaister** [comment]
Yes that is the item! I do speak english

**Comment by HgAlexx** [comment]
Hello, I've tested this item with english client, working fine here, please try to clear the cache with:
/buffet clear
then
/buffet scan
