### ISSUE TITLE
bests.conjuredFood and bests.food have stopped working in WoW Classic

### ISSUE THREAD

**Issue by missing-string** [HgAlexx/Buffet#20]
**Describe the bug**
Food does not show up as the macro in WoW Classic at the moment. My drink one works flawlessly, but the food one has stopped working. The code between the two are almost identical with just replacements for the relevant item type. Whether I have conjured food or normal food in my inventory, it just shows the 1 icon (a question mark) permanently.

Drink
local bests = ...
local drink = bests.conjuredDrink or bests.drink
local body = "#showtooltip\n/use "
body = body .. "item:" .. (drink or "1")
return body

Eat
local bests = ...
local drink = bests.conjuredFood or bests.food
local body = "#showtooltip\n/use "
body = body .. "item:" .. (eat or "1")
return body

**To Reproduce**
Use the above "Eat" macro and summon some food/buy some food from a vendor.

**Related Item**
N/A - all food affected.

**Language**
English

**Comment by HgAlexx** [comment]
There is a type in your food macro, second line should be 👍 
`local eat = bests.conjuredFood or bests.food`
since you use the "eat" variable in last line.

**Comment by missing-string** [comment]
Corrected and tested - working fine now. Apologies for wasting your time.

**Comment by HgAlexx** [comment]
No worry ;)
