### ISSUE TITLE
Managem

### ISSUE THREAD

**Issue by vBaustad** [HgAlexx/Buffet#25]
**Describe the bug**
bests.manaGem does not seem to recognize mage mana gems in tbc. Unsure if this "manaGem" refers to something else but would greatly appreciate it working for those as well.

**To Reproduce**
Steps to reproduce the behavior if applicable:
have a mage character, create managems, make custom macro and check for bests.manaGem

**Related Item**
Please provide a WowHead link to the related item if applicable:
https://tbc.wowhead.com/item=8008/mana-ruby

**Language**
Please specify the language of your wow client:
English

**Comment by HgAlexx** [comment]
Hello,
Should be fix in last release, version 2.5.1.78 !

**Comment by vBaustad** [comment]
awesome! Seems like it works now! Also, would you be able to implement a feature for ignoring certain items? Like say i don't want to use my absolute best mana potion, rather one below.

**Comment by HgAlexx** [comment]
Should be possible, however I'm not sure how I'll do it yet :)

**Comment by vBaustad** [comment]
one ghetto fix i guess could be having a separate list of 1 lower than bests and allow the use of those too, so you could have 
mana  = bests.manaGem or secondbests.manaPotion. Idk, just throwing out first idea i thought of.

or you could implement an ignore command that the custom macros can read where players would add in IDs for items to ignore in their custom macro builder! 

Itemignore = 54249, 41999, 91241 etc

**Comment by HgAlexx** [comment]
I leaning toward the ignore list but I have another idea.
However, don't expect this feature quickly, I won't have much time except to fix issue on the coming days.
