### ISSUE TITLE
PvP Support

### ISSUE THREAD

**Issue by nSimonFR** [HgAlexx/Buffet#3]
With the release of Battlegrounds, there are tons of new items that have been released that are unsupported by this addon, to name a few:
- Alterac Heavy Runecloth Bandage
- Major Healing Draught

Most of these are usable only in battlegrounds but I'm sure it's something addons can detect.

**Comment by nSimonFR** [comment]
From what I could understand from the code, I managed to add restrictions to Const.lua, you can see the changes here: https://github.com/nSimonFR/Buffet/blob/master/Const.lua
Maybe that can help you out

**Comment by HgAlexx** [comment]
Hi / Salut !

Je n'ai pas encore eu le temps de finaliser la version Classic, il manque également les pierre de soin des démo. Je suis entrain faire un refactoring pour séparer la logique Retail de la logique Classic et je pensais finaliser Classic après.

En attendand, j'ai ajouté vos modifications à Const.lua (Merci !) et j'ai activé la détections de changement de zone ainsi que la vérification sur les restrictions pour Classic.

Vous pouvez tester ces modifications avec la build "8.2.5.59-Beta".

Je n'ai pu tester que certains des items qui semblent bien reconnus. N'hésitez pas à me dire si il y a toujours un problème ou si ça fonctionne correctement !

**Comment by nSimonFR** [comment]
J'ai pu tester les changements de 8.2.5.59-Beta, il semblerait que le seul item qui soit reconnu et propose dans les macros soit la Pierre de Foyer (item:6948), cela meme apres un `/buffet clear`

**Comment by HgAlexx** [comment]
Si les macro propose la pierre de foyer c'est qu'aucun item n'a été détecté (c'est la valeur par défaut).

Les changements de la dernière version n'auraient pas du affecter les autres items, c'est étrange.
Je vais refaire quelques tests, il y a peut être eu une mise à jour cette nuit ou ce matin qui cause votre soucis.

Vous pouvez vérifier si un item est correctement scanné/parsé via la commande:
/buffet debug [item]

Cela permettra au moins de valider que tous les nouveaux items sont bien reconnu.

Pour le moment je n'ai pas pu tester Alterac, je n'ai pu tester que Warsong pour voir si l'Id d'instance était correct. Je testerai Alterac dans le weekend.

**Comment by HgAlexx** [comment]
Je viens de tester la dernière build, aucun soucis de mon coté :(
Peut-être un conflit avec un addon récemment mis à jour ?
