### ISSUE TITLE
Bottled nethergon energy not prioritized in relevant zones.

### ISSUE THREAD

**Issue by mooblia** [HgAlexx/Buffet#30]
Hey so [item=32905/bottled-nethergon-vapor](https://tbc.wowhead.com/item=32905/bottled-nethergon-vapor) correctly is prioritized over [item=22829/super-healing-potion](https://tbc.wowhead.com/item=22829/super-healing-potion)
when in relevant zones.

 

However it is not the case for [item=32902/bottled-nethergon-energy](https://tbc.wowhead.com/item=32902/bottled-nethergon-energy) over [item=22832/super-mana-potion](https://tbc.wowhead.com/item=22832/super-mana-potion)

Thanks in advance!

**Comment by HgAlexx** [comment]
Should be fix in the incoming release.

**Comment by HgAlexx** [comment]
Please try the last beta release.

**Comment by mooblia** [comment]
Works excellent here in Botanica right now!
