### ISSUE TITLE
Item Scanning seems broken.

### ISSUE THREAD

**Issue by Crelam** [HgAlexx/Buffet#31]
**Describe the bug**

Buffet seems to be silently failing.  Tried /buffet clear with no fix, also tried to /buffet debug an Ethereal Pomegranate and got the message "ScanTooltip Failed".  Also tried some other food items and health potions and got the same message.

**To Reproduce**
Steps to reproduce the behavior if applicable:
Log into retail and notice that the macros are blank.  Also try to debug an items.

**Related Item**
Please provide a WowHead link to the related item if applicable:

**Language**
Please specify the language of your wow client:
English

**Comment by Crelam** [comment]
I'm also getting this lua error when I try to do a debug:

2x Buffet\Buffet-9.0.2.75.lua:834: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Buffet\Buffet-9.0.2.75.lua"]:834: in function `SlashHandler'
[string "@Buffet\Buffet-9.0.2.75.lua"]:902: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5157: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4821: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4857: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>
[string "=[C]"]: ?

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by HgAlexx** [comment]
I cannot reproduce the issue on my side, can you try with only Buffet enable ? it might be an incompatibility with another addon.
Note that the tooltip can fail the first time when using /buffet debug, try a second time. Wow sometime a few seconds to load the tootlip from the server.

**Comment by Crelam** [comment]
I have run Buffet alone with no other addons, but the issue remains.

To further troubleshoot, I also removed the SavedVariables files associated with Buffet.

Curiously, I noticed there is only one item listed in the account level SV file which is the Deep Fried Seraph Tenders, which is an item in my bags but is a more uncommon food item.   I have other food items, health potions, and bandages in my bags but they don't seem to scan or enter the itemCache.

BuffetItemDB = {
	["itemCache"] = {
		[182737] = {
			["itemId"] = 182737,
			["isPct"] = false,
			["isPotion"] = false,
			["itemClassId"] = 0,
			["isMana"] = true,
			["mana"] = 40000,
			["isHealth"] = true,
			["isWellFed"] = true,
			["isFoodAndDrink"] = false,
			["isConjured"] = false,
			["health"] = 30000,
			["isBandage"] = false,
			["isOverTime"] = false,
			["isRestricted"] = false,
			["overTime"] = 0,
			["itemSubClassId"] = 5,
		},
	},
	["customMacros"] = {
	},
	["version"] = "9.0.2.75",
	["nextScanDelay"] = 10,
	["build"] = 39229,
}

Also, don't mind the 10 sec scan delay, that is just something I was doing to further troubleshoot.

**Comment by HgAlexx** [comment]
One thing I've just notice, did you rename some files ?
The core file should be named Buffet.lua but seams to be named Buffet-9.0.2.75.lua from the stack above.

Did you download it from curse?
Also, do you play using English locale ?

I'll do more test later today

**Comment by Crelam** [comment]
Yes, I play on NA, English, Retail Servers.  Deathwing to be precise.

As to the filename: I believe thats just how bugsack reports the error.  Including the version number along with the file name.

The files should be pulled straight from Curse using Acidweb's Cursebreaker addon updater.  However just to eliminate any variance, I have manually downloaded and installed version 9.0.2.75 again.  After retesting the issue still persists.

**Comment by HgAlexx** [comment]
Ok nvm, I found the issue :)
Blizzard decided to rework the tooltip of most found on Retails breaking most of them.
I'll push a fix asap, it will be in the next beta version for retails

**Comment by rml9ty** [comment]
Works fine again with the newest version. Thanks for the update!

**Comment by Crelam** [comment]
Can confirm, 9.1.0.80_Beta fixes my issue.  Thanks for your time and effort.
