### ISSUE TITLE
"/buffet bests" returns error

### ISSUE THREAD

**Issue by Zautix** [HgAlexx/Buffet#37]
Buffet\Buffet-2.5.1.78.lua:834: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Buffet\Buffet-2.5.1.78.lua"]:834: in function `SlashHandler'
[string "@Buffet\Buffet-2.5.1.78.lua"]:902: in function `?'
[string "@FrameXML\ChatFrame.lua"]:4825: in function <FrameXML\ChatFrame.lua:4771>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4488: in function <FrameXML\ChatFrame.lua:4487>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4524: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

**Language**
enUS

**Comment by HgAlexx** [comment]
I think this is fixed here but I'm 3 months late for a release :(
I haven't got time to play wow in the last 2 months and my local code is still in the middle of implementing a fix for arena.

I'll try to find some time Sunday to fix most issue and do a proper release.
