### ISSUE TITLE
Not working with several [30K health + 40K mana] foods.

### ISSUE THREAD

**Issue by krstcs** [HgAlexx/Buffet#40]
**Describe the bug**
The system doesn't pick up several of the foods as available when running "/buffet scan" and shows nothing when running "/buffet bests" even though I have at least 6 stacks of 3 different foods that provide 30k health and 40k mana (for example items 174284 @ 56, 179286 @ 1,  174283 @ 35).

Right now the food macro shows nothing on any of my toons at all (just the hearthstone default).  I've uninstalled and reinstalled, I've edited the code locally to try to find the issue, remade the macros, etc., but nothing works (I got it to work once by commenting out a couple of lines of code, but I don't remember what it was).

**To Reproduce**
Type "/buffet scan"
Type "/buffet bests" -> nothing displayed

**Related Item**
I use ArkInventory for management, but that shouldn't affect the bag system that buffet uses.

**Language**
Please specify the language of your wow client: enUS

**Comment by HgAlexx** [comment]
Hello,
I haven't been able to play WoW since august, I'll try to have a look this weekend, it is probably a changes in the text format of some items.

Can you give me wowhead link of those items please ?

Thank you.

**Comment by krstcs** [comment]
https://www.wowhead.com/item=174284
https://www.wowhead.com/item=179286
https://www.wowhead.com/item=174283
