### ISSUE TITLE
No Macros

### ISSUE THREAD

**Issue by EzeRage** [HgAlexx/Buffet#41]
**Describe the bug**
Only addon installed and no macros are made.

Addon reacts to commands ingame but still no macros

**To Reproduce**
Install addon and launch game

**Language**
English

**Comment by HgAlexx** [comment]
Did you dragged the macro from the config panel ?

Buffet won't create all macros by default, you need to open the configuration panel and click on the macros' button you want, drag the macro into an action bar slot.

**Comment by EzeRage** [comment]
Unable to open the config panel.

**Comment by EzeRage** [comment]
Nevermind. Thank you HgAlexx was able to get the macros created.
