### ISSUE TITLE
Making Buffet available elsewhere than Curse

### ISSUE THREAD

**Issue by bronze** [HgAlexx/Buffet#42]
**Is your feature request related to a problem? Please describe.**
Since CurseForge is restricting access to their API for updating addons, could Buffet be made available elsewhere?

**Describe the solution you'd like**
WowUp supports GitHub as a source. That seems practical. [link here:[https://wowup.io/guide/wowup/hub](https://wowup.io/guide/wowup/hub)]

**Describe alternatives you've considered**
Wago.io and WowInterface are solid options too.

**Comment by HgAlexx** [comment]
Fix with #43
