### ISSUE TITLE
Repository is incompatible with WoWUp

### ISSUE THREAD

**Issue by KevinTyrrell** [HgAlexx/Buffet#43]
Installing Buffet for TBC using WoWUp by inputting the URL of this repository yields the following error:

![image](https://user-images.githubusercontent.com/12791400/170844990-4c5b5547-fe68-418a-a1a8-c3ea69470fe9.png)

The URL used for installing for the above image was: https://github.com/HgAlexx/Buffet

In order for WoWUp to recognize this repository, you must create a [Release](https://github.com/HgAlexx/Buffet/releases) that includes a `.zip` file whose file name ends with `-bcc`. For example the zip file may be called `Buffetv.1.0.0-bcc.zip`

Given the popularity of WoWUp and the lack of Curseforge as an option, it is highly recommended you make this repository compatible with WoWUp in order to allow ease-of-use when installing.

**Comment by HgAlexx** [comment]
All 3 release have been added to github, zip name should be ok for WowUp, let me know.

**Comment by KevinTyrrell** [comment]
Installed and works just fine. Thank you!
