### ISSUE TITLE
WOTLK Support

### ISSUE THREAD

**Issue by maximus210793** [HgAlexx/Buffet#44]
Hi, 
can you update for WOTLK Classic please?
Would be awesome.
Thanks in advance!

**Comment by HgAlexx** [comment]
Done.

https://github.com/HgAlexx/Buffet/releases/tag/9.2.7.83_Beta

I currently don't have access to Wow Classic so it is an UNTESTED beta release.

Please tell me if you have any issue with it ;)

**Comment by maximus210793** [comment]
Hi,
I will test it thanks. The previous version did not recognize the WOTLK Prepatch Food in my bags.
Will you also upload the addon to curseforge?
Thanks in advance.

**Comment by HgAlexx** [comment]
Already done. I find out why curse was not doing the automatic packaging ;)
https://www.curseforge.com/wow/addons/buffet/files/3961064

I also find out that I can access the PTR server without subscription so I can do limited testing.
