### ISSUE TITLE
Excessive Console Output

### ISSUE THREAD

**Issue by KevinTyrrell** [HgAlexx/Buffet#46]
A recent update seems to have increased the amount of printed text to the chat frame. I'm not sure if this was for debug reasons but it's quite disruptive. It does seem like there are quite a lot of items being cached and many various mundane items that have the `5 failed attempt on:` message.

I'd be happy to look into the source code if this might be a bug, but my guess is its a debug flag that wasn't turned off.

![image](https://user-images.githubusercontent.com/12791400/188366081-cb648f7d-06b2-480a-9ba7-bc61a5971d30.png)

**Comment by KevinTyrrell** [comment]
![image](https://user-images.githubusercontent.com/12791400/188420124-b5bccbb5-441d-47a8-8af5-10604a32ca6e.png)

I believe I'm on the latest release of Buffet. WoWUp claims it's `Buffet_9.2.7.86_Beta.zip`. Is it possible the issue persisted into that version, or is there a newer version hosted elsewhere?

**Comment by HgAlexx** [comment]
The flag is properly set to false on the curse version, but true on the github version (used by WowUp) and it is my fault :)
I've updated the zip file for the last release on github, try to remove and reinstall Buffet from WowUp.
You might need to force redownload if WowUp keep a cache.
You can also download the release here and install it manually:
https://github.com/HgAlexx/Buffet/releases/tag/9.2.7.86_Beta
