### ISSUE TITLE
Harvest festival consumables are not considered

### ISSUE THREAD

**Issue by red13dotnet** [HgAlexx/Buffet#47]
**Describe the bug**
Harvest festival consumables are not added to food or drink macros

**To Reproduce**
3.4.0 WOTLK Prepatch
Have the items Harvest Nectar,Boar, Fish or Fruit in inventory.
Attempt to access via food only or drink only macro

**Related Item**
https://www.wowhead.com/wotlk/item=19997/harvest-nectar
Buffet: Item [Harvest Nectar]:
Buffet: - Is health: No
Buffet: - Is mana: Yes
Buffet: - Is well fed: No
Buffet: - Is conjured: No
Buffet: - Is percent: No
Buffet: - Is food and drink: Yes
Buffet: - Is potion: No
Buffet: - Is bandage: No
Buffet: - Is over time: Yes
Buffet: - Is restricted:  No
Buffet: - health value: 0
Buffet: - mana value: 0
Buffet: - itemClassId: 0
Buffet: - itemSubClassId: 0

https://www.wowhead.com/wotlk/item=19995/harvest-boar
Buffet: Item [Harvest Boar]:
Buffet: - Is health: Yes
Buffet: - Is mana: No
Buffet: - Is well fed: No
Buffet: - Is conjured: No
Buffet: - Is percent: No
Buffet: - Is food and drink: Yes
Buffet: - Is potion: No
Buffet: - Is bandage: No
Buffet: - Is over time: Yes
Buffet: - Is restricted:  No
Buffet: - health value: 0
Buffet: - mana value: 0
Buffet: - itemClassId: 0
Buffet: - itemSubClassId: 5

https://www.wowhead.com/wotlk/item=19996/harvest-fish
Buffet: Item [Harvest Fish]:
Buffet: - Is health: Yes
Buffet: - Is mana: No
Buffet: - Is well fed: No
Buffet: - Is conjured: No
Buffet: - Is percent: No
Buffet: - Is food and drink: Yes
Buffet: - Is potion: No
Buffet: - Is bandage: No
Buffet: - Is over time: Yes
Buffet: - Is restricted:  No
Buffet: - health value: 0
Buffet: - mana value: 0
Buffet: - itemClassId: 0
Buffet: - itemSubClassId: 5

https://www.wowhead.com/wotlk/item=19994/harvest-fruit
Buffet: Item [Harvest Fruit]:
Buffet: - Is health: Yes
Buffet: - Is mana: No
Buffet: - Is well fed: No
Buffet: - Is conjured: No
Buffet: - Is percent: No
Buffet: - Is food and drink: Yes
Buffet: - Is potion: No
Buffet: - Is bandage: No
Buffet: - Is over time: Yes
Buffet: - Is restricted:  No
Buffet: - health value: 0
Buffet: - mana value: 0
Buffet: - itemClassId: 0
Buffet: - itemSubClassId: 5

**Language**
EnUS

**Comment by HgAlexx** [comment]
I love a proper bug report :D

A new release is being built on curse, and will be added to github when ready ;)

**Comment by HgAlexx** [comment]
Of course Curse is stuck on processing...
Anyway, the release is available here:
https://github.com/HgAlexx/Buffet/releases/tag/87_Beta

**Comment by red13dotnet** [comment]
Confirmed working on my end.

Thank you!
