### ISSUE TITLE
WOTLK Mana Gem

### ISSUE THREAD

**Issue by PoodyCZ** [HgAlexx/Buffet#49]
**Describe the bug**
Mana gem not included in MP macro

**To Reproduce**
Have a mana gem, get in combat

**Related Item**
Please provide a WowHead link to the related item if applicable: [Mana Agate](https://www.wowhead.com/wotlk/item=5514/mana-agate)

**Language**
EN

**Comment by HgAlexx** [comment]
This was supposed to be fix with #45, are you using the last available beta version (87_Beta) ?

**Comment by PoodyCZ** [comment]
![image](https://user-images.githubusercontent.com/17796499/192447624-034ee169-27b1-4a0a-96a8-9b10f3f4b6e7.png)
Yes

I just found the option for consumable modifier, I had default mod:shift for managem
However even with this it doesnt seem to work.
I removed mod:shift altogether
I moved mod:shift to potions and it worked OK for health potion even on an old macro created a week ago
All the MP macros were created newly for testing.

**Comment by HgAlexx** [comment]
The PTR for Wrath is currently down so I'm unable to test :(

Can you run this command:
/buffet debug [Mana Agate]

(shift click the item to added it to the command)

Can you also give a me a screenshot of the item tooltips?

Thanks.

**Comment by PoodyCZ** [comment]
I hope it's not an issue with low level (30)

![image](https://user-images.githubusercontent.com/17796499/192470463-cbf9f2e0-34dd-440b-b0b3-cff2e87edf20.png)

![image](https://user-images.githubusercontent.com/17796499/192470810-30461434-e062-4cad-b952-56889f3f1a3f.png)

**Comment by HgAlexx** [comment]
Looks like it properly detected, can you run:
/buffet bests

Be sure to have a gem in your bag, also, maybe run /buffet clear first :)

Thx !

**Comment by PoodyCZ** [comment]
Bests without clear
![image](https://user-images.githubusercontent.com/17796499/192471754-a0d661cf-7b34-4591-ae4d-1cbbeaebb0e8.png)
Bests after clear
![image](https://user-images.githubusercontent.com/17796499/192471848-e411f720-d498-40bf-9fbc-e4b946feaf41.png)

:|

**Comment by HgAlexx** [comment]
I've find the issue, I'll push a fix asap

**Comment by HgAlexx** [comment]
I forget to comment but beta 88 is available here and on curse, if the issue is resolved you can close it :)

**Comment by PoodyCZ** [comment]
It appears to be fixed, perfect :) Good job and thank you for maintaining the repo
