### ISSUE TITLE
Runic Mana Potion is prioritized over Runic Mana Injector for engineers (WotLK)

### ISSUE THREAD

**Issue by atropon** [HgAlexx/Buffet#50]
This issue concerns Wrath of the Lich King Classic.

Runic Mana Potion Injector yields more mana than Runic Mana Potion, for engineers.
Consequently, the priority of Runic Mana Potion Injector is supposed to be higher than Runic Mana Potion (for engineers).

Currently, Runic Mana Potion is prioritized over Runic Mana Potion Injector regardless of profession.

Probably, the same issue does occur for all injectors and their respective potions; however, I only observed it for the Runic Mana Potion Injector.

**Comment by HgAlexx** [comment]
Can you give me item ids ou wowhead link ? thx

**Comment by hititdoc** [comment]
For engineers:

- [Runic Healing Injector](https://www.wowhead.com/wotlk/item=41166/runic-healing-injector) should have higher priority than [Runic Healing Potion](https://www.wowhead.com/wotlk/item=33447/runic-healing-potion)
- [Runic Mana Injector](https://www.wowhead.com/wotlk/item=42545/runic-mana-injector) should have higher priority than [Runic Mana Potion](https://www.wowhead.com/wotlk/item=33448/runic-mana-potion)

Non-engineers can use these injectors, but there is no difference in healing or mana gain compared to the non-injectors.

**Comment by HgAlexx** [comment]
I should have fix soon however I don't have an engineer so you'll have to test it and tell me if it's working :)
Do you know how much more health/mana you get ? I read +25% but I'm not sure about it.

**Comment by hititdoc** [comment]
Yes, I get around 5300 mana back on average, which is roughly +25% of 4300.

**Comment by hititdoc** [comment]
Confirmed working. Thank you.
