### ISSUE TITLE
[WOTLK] Black jelly not being considered

### ISSUE THREAD

**Issue by gustavo-momente** [HgAlexx/Buffet#51]
**Describe the bug**
[Black Jelly](https://www.wowhead.com/wotlk/item=45932/black-jelly) is a food that restores both mana and health and isn't being considered. I think it should work the same as conjured mage food.

**To Reproduce**
Have [Black Jelly](https://www.wowhead.com/wotlk/item=45932/black-jelly) in bags and check that macros don't consider it

**Related Item**
- [Black Jelly](https://www.wowhead.com/wotlk/item=45932/black-jelly)

**Language**
- Client is en-us

**Comment by HgAlexx** [comment]
This should be fix in version 90_Beta available on curse and here:
https://github.com/HgAlexx/Buffet/releases/tag/90_Beta
