### ISSUE TITLE
How can I manually add item to ignore list?

### ISSUE THREAD

**Issue by hasnogaems** [HgAlexx/Buffet#52]
Certain food I do not wanna consume very often, how can I ignore it?

**Comment by HgAlexx** [comment]
It is not possible but I can add this feature, shouldn't be too difficult.

**Comment by HgAlexx** [comment]
The feature is available in the last beta version on curse or here:
https://github.com/HgAlexx/Buffet/releases/tag/91_Beta

use the following command:
/buffet ignore-add <itemLink>
/buffet ignore-remove <itemLink>
/buffet ignore-list

**Comment by hasnogaems** [comment]
Tremendous!
