### ISSUE TITLE
Add Well Fed buff detection for custom macro.

### ISSUE THREAD

**Issue by meyverick** [HgAlexx/Buffet#53]
**Is your feature request related to a problem? Please describe.**
I'm frustrated to not be able to make a custom macro detecting if I'm Well Fed or not.

**Describe the solution you'd like**
A boolean variable to check if I'm Well Fed or not. `buff.wellFed`

**Comment by meyverick** [comment]
Discovered that your AddOn allows us to use WoW API so I managed to make a custom script.

**Comment by HgAlexx** [comment]
Beware that the custom code that make the macro is not what is run when you press the macro button.

The custom code you write to generate the macro is only run out of combat and only when the following events occur :
- bags content changes
- player level changes
- player max health/mana changes
- player enter/leave a zone (or sub-zone)

If the player was in combat when one of these events occurred, the macro will be updated as soon as the player leave combat.
