### ISSUE TITLE
LUA error with version 92

### ISSUE THREAD

**Issue by Fraktyl** [HgAlexx/Buffet#56]
**Describe the bug**
LUA Error when closing the options menu in the pre-patch.  Version 9.2 released on 10/24

**To Reproduce**
Open options menu and close it

**Related Item**
N/A

**Language**
English

LUA Error:
2x Interface/AddOns/Buffet/Config.lua:607: attempt to index field 'nameEdit' (a nil value)
[string "@Interface/AddOns/Buffet/Config.lua"]:607: in function `loadActive'
[string "@Interface/AddOns/Buffet/Config.lua"]:625: in function `reset'
[string "@Interface/AddOns/Buffet/Config.lua"]:815: in function `OnCommit'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:525: in function <...erface/SharedXML/Settings/Blizzard_SettingsPanel.lua:523>
[string "=[C]"]: in function `xpcall'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:501: in function <...erface/SharedXML/Settings/Blizzard_SettingsPanel.lua:498>
[string "=[C]"]: in function `secureexecuterange'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:505: in function <...erface/SharedXML/Settings/Blizzard_SettingsPanel.lua:498>
[string "=[C]"]: in function `secureexecuterange'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:509: in function `ForEachCanvas'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:523: in function `CommitCanvases'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:247: in function `Commit'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:276: in function `ExitWithCommit'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:257: in function `Close'
[string "@Interface/SharedXML/Settings/Blizzard_SettingsPanel.lua"]:44: in function `onCloseCallback'
[string "@Interface/SharedXML/SharedUIPanelTemplates.lua"]:127: in function <Interface/SharedXML/SharedUIPanelTemplates.lua:122>

**Comment by HgAlexx** [comment]
Reproduced, working on it ;)

**Comment by HgAlexx** [comment]
Fixed in version 93 available here and soon on curse.
