### ISSUE TITLE
Version difference between GitHub and CurseForge

### ISSUE THREAD

**Issue by tanrak** [HgAlexx/Buffet#58]
Hello, thank you for maintaining this fine addon from Tekkub. I have noticed that the version here under Releases is older than the version on CurseForge. I use one of the many third party updaters that have drop CurseForge support for the update. Therefore, it would be nice if the versions here and at Github would match.

**Comment by HgAlexx** [comment]
Oups, my bad !

I have an issue to fix, so I'll do a new release on curse and will update Github accordingly.

**Comment by HgAlexx** [comment]
Version 96 available !
