### ISSUE TITLE
retail vendor water

### ISSUE THREAD

**Issue by rml9ty** [HgAlexx/Buffet#59]
https://wowhead.com/item=194684 valdrakken vendor water isnt counted as food/drink. is there a list where one can add it manually? (:

**Comment by HgAlexx** [comment]
I'll have a look later today, in which language are you playing ?

**Comment by HgAlexx** [comment]
This item is working fine one my end. Tested with English and French language for text. If you use another language please tell me.

Also, please provide me the output of:
/buffet debug <item>

Thank you.
