### ISSUE TITLE
REQ: Limit Horrific Delicacies to Horrific Vision zones

### ISSUE THREAD

**Issue by doktorstick** [HgAlexx/Buffet#6]
I have a request that the horrific delicacies be limited to the horrific vision zones (the horrific Orgrimmar and Stormwind). Or, if not completely filtered out, only used if no other food is available.

The foods are:

- Baked Voidfin [314959]
- Dubious Delight [314961]
- Ghastly Goulash [314962] 
- Grilled Gnasher [314963]
- K'Bab [314960]

**Comment by HgAlexx** [comment]
Hello,

Those items should not show up at all since there are "well fed" foods.

I've just pushed a beta release, can you check if the issue is still present ?
https://www.curseforge.com/wow/addons/buffet/files/2888166

Thanks!

**Comment by doktorstick** [comment]
I didn't test the link you posted as I use `git` directly. It still has those foods (K'Bab, specifically) after a `/buffet clear`.

```
commit f1c6135c7265d144dccb024221aafec3c7de66d3 (HEAD -> master, tag: 8.3.0.60-Beta, origin/master, origin/HEAD)
Author: HgAlexx <mzhg@13fr.com>
Date:   Mon Feb 24 22:25:56 2020 +0100                                               
    Update changelog.txt
```

**Comment by HgAlexx** [comment]
Hi,
Which localization are you using (for ingame text) ?
I'll have to test them. Sometime Blizzard being Blizzard, they like to complicate thing for me :)

You can also try the /buffet debug [item] and see if the "is well fed" is "yes".
If you want to debug the issue, you and uncomment the Debug function in Utility.

**Comment by HgAlexx** [comment]
Hi again,
I have a explanation for "K'Bab". It's not a well fed food so it's not filtered out.
https://www.wowhead.com/item=174351/kbab

This one will need to be restricted based on zone or other means.

**Comment by doktorstick** [comment]
English and here's the tail-end of the debug output:
![image](https://user-images.githubusercontent.com/1571413/75311156-852e8080-581b-11ea-812b-0d6f935ee8c8.png)

**Comment by HgAlexx** [comment]
Hello!

I pushed small changes to exclude K'Bab from valid food.

If you want to allow it only in vision, check the end "Retail/ConstRetail.lua".
I've added a few map/instance id but I'm unable to test them as I don't have access to visions yet (sadly not much time to play atm).

To help you debug this, I've added a command: /buffet showzone
This command is only available from source (commented out in build).
/buffet debug will also show if item is retricted or not now.

Regarding the IDs, you were not far off, you gave me the id of the spell to craft the food, good enough to find them ;)

Thank for your help!

**Comment by doktorstick** [comment]
Initial tests out of visions are positive. I haven’t been into a vision yet to know what Buffet does.

**Comment by HgAlexx** [comment]
Hi,
I know have access to some visions, item is properly filtered out (everywhere) with pushed code.
I'll push the instance ids I got asap.

**Comment by HgAlexx** [comment]
Hi,
Ids pushed. Since these foods are "buff" food, I'll keep them excluded for the release.
However, I'll find a way for end users to customize restrictions later (as a setting).
