### ISSUE TITLE
Classic - healthstone debug incorrect info and behaviour 

### ISSUE THREAD

**Issue by Or1j1n** [HgAlexx/Buffet#61]
On Classic, it seems that buffet think Healthstone is a potion and not conjured item.
![image](https://github.com/HgAlexx/Buffet/assets/8409935/6a57545f-f283-41d8-b38b-c5b2cbf99169)
![image](https://github.com/HgAlexx/Buffet/assets/8409935/f08e7861-8b52-48aa-a8b2-9ff5f38272d8)
![image](https://github.com/HgAlexx/Buffet/assets/8409935/998d5501-69b4-4713-b892-864141dceb6d)

When using bests.healthstone with a healthstone in inventory (id:19009), he doesnt show anything.

```
local bests, cache = ... -- Keep this

local healthstone = bests.healthstone or 6948

return "#showtooltip\n/cast item:" .. healthstone, "INV_Misc_QuestionMark"
```

**Comment by HgAlexx** [comment]
Hello,
Can you get me a screenshot of the item(s) tooltip ?

**Comment by HgAlexx** [comment]
Nevermind, I think I find the issue, release underway.

**Comment by Or1j1n** [comment]
damn, you're fast, ty
