### ISSUE TITLE
Template for Macro Lua Source Code doesnt appear anymore

### ISSUE THREAD

**Issue by Or1j1n** [HgAlexx/Buffet#62]
**Describe the bug**
The windows for Macro Lua Source code is empty when clicking on Buffer>Custom Macro>New Macro.
Before it showed a template for custom macro.

![image](https://github.com/HgAlexx/Buffet/assets/8409935/da1081bd-1921-4480-9c9a-0cb05ee4e83f)

**To Reproduce**
I have only have Buffet-98 activated, playing on Classic Era 1.14.3
click on Buffer>Custom Macro>New Macro

**Language**
EN

**Comment by HgAlexx** [comment]
Hello,

I've just tested on the Classic Era PTR and I cannot reproduce the issue. Every functions seams to be working.

Note that the last PTR version use the new UI : https://i.imgur.com/YWjon5i.png
This might be related as I have updated Buffet to support it recently for Retail and WotLK.

Sadly I'm unable to test on Classic live servers at the moment.

Here the template in the mean time:

```
local bests, cache = ... -- Keep this

-- Available categories: contains the item id or nil
-- bests.bandage
-- bests.rune
-- bests.conjuredFood
-- bests.conjuredDrink
-- bests.food
-- bests.drink
-- bests.wellFedFood
-- bests.wellFedDrink
-- bests.healthstone
-- bests.manaGem
-- bests.healthPotion
-- bests.manaPotion

-- Example for best food with default to hearthstone
local bestfood = bests.conjuredFood or bests.food or 6948

-- Must return: body [, icon]
return "#showtooltip\n/cast item:" .. bestfood, "INV_Misc_QuestionMark"

```

**Comment by Or1j1n** [comment]
I can confirm that it works flawlessly on PTR.

I suppose i will work again on Classic when they will update to the PTR Build version.

Once again, thanks for the quick answer

**Comment by Or1j1n** [comment]
I just realized that i wasnt clear on my issue description.

Not only when i click new macro, the template doesnt show but i cant type anything in the textbox and multitextbox.

**Comment by HgAlexx** [comment]
Classic Era will get the update on August 24th.
In the mean time, you can try version 97, it should work.

**Comment by Or1j1n** [comment]
resolved. ty

**Comment by Or1j1n** [comment]
ty
