### ISSUE TITLE
Classic - missing Sweet Nectar, itemID 1708

### ISSUE THREAD

**Issue by fireymerlin** [HgAlexx/Buffet#63]
Sweet Nectar is not showing on the macro for mana.
I'm level 25 and can use Sweet Nectar

**Comment by HgAlexx** [comment]
Hello,

Which version of Wow ? Retail ? WotLK? Classic ?
Which language for text ?

Can you run the following command and show me the output:
/buffet debug <ItemLink>

Thank you !

**Comment by fireymerlin** [comment]
I have addon TipTac showing the ItemID
![image](https://github.com/HgAlexx/Buffet/assets/441778/775d52d3-2ce6-4851-babb-baef7ab2ee75)

**Comment by fireymerlin** [comment]
I ran the debug command.  Here is the output, multiple screenshots:
![image](https://github.com/HgAlexx/Buffet/assets/441778/44f27fa0-c17c-43a8-94ed-9612299e846c)

**Comment by fireymerlin** [comment]
![image](https://github.com/HgAlexx/Buffet/assets/441778/71c5e82b-02ea-4aff-9670-82506556e9b7)

**Comment by fireymerlin** [comment]
Here is what the macro is showing on my toolbar (the tooltip of the item) which is a lower mana item:
![image](https://github.com/HgAlexx/Buffet/assets/441778/0917e761-047a-4d9f-8d4b-1b2a46cd26fa)

**Comment by fireymerlin** [comment]
I meant actionbar, not toolbar.

I'd be happy to do any testing you want.  I used to be a programmer and am familiar with lua coding.

**Comment by HgAlexx** [comment]
I think I found the issue, I'm surprise I didn't notice it sooner!

Update coming soon :)

**Comment by HgAlexx** [comment]
New release 99 available here:
https://www.wowace.com/projects/buffet/files/4804798

**Comment by fireymerlin** [comment]
thank you
