### ISSUE TITLE
Cataclysm Classic bug/errors

### ISSUE THREAD

**Issue by AutolycusWolf** [HgAlexx/Buffet#67]
**Describe the bug**
Lua errors upon logging-in on Cataclysm Classic pre-patch.

**To Reproduce**
Just logging-in

**Language**
Please specify the language of your wow client: English

Don't know if this is of any help but this is what I'm getting:

1x Buffet/Buffet.lua:319: attempt to call field 'IsValidItemClasses' (a nil value)
[string "@Buffet/Buffet.lua"]:319: in function `Scan'
[string "@Buffet/Buffet.lua"]:271: in function <Buffet/Buffet.lua:266>

Locals:
self = <table> {
 scanAttempt = <table> {
 }
 bests = <table> {
 }
 OnTimerCallback = <function> defined @Buffet/Buffet.lua:266
 itemCache = <table> {
 }
 customMacros = <table> {
 }
 CompileSource = <function> defined @Buffet/Buffet.lua:543
 SetBest = <function> defined @Buffet/Buffet.lua:802
 Scan = <function> defined @Buffet/Buffet.lua:275
 RunChunk = <function> defined @Buffet/Buffet.lua:525
 EditDefault = <function> defined @Buffet/Buffet.lua:679
 EnableDelayedScan = <function> defined @Buffet/Buffet.lua:258
 EditFoodOnly = <function> defined @Buffet/Buffet.lua:726
 ResetAvailableItems = <function> defined @Buffet/Buffet.lua:244
 firstRun = true
 SetAvailable = <function> defined @Buffet/Buffet.lua:813
 ignoredItemCache = <table> {
 }
 AvailableItemsBeautifier = <function> defined @Buffet/Buffet.lua:603
 nextScan = 0
 db = <table> {
 }
 nextScanDelay = 1.200000
 playerMana = 3963
 BestsBeautifier = <function> defined @Buffet/Buffet.lua:583
 Edit = <function> defined @Buffet/Buffet.lua:661
 PrintItemData = <function> defined @Buffet/Buffet.lua:1004
 playerHealth = 7054
 QueueScan = <function> defined @Buffet/Buffet.lua:250
 Buffet = Frame {
 }
 MakeNewItemData = <function> defined @Buffet/Buffet.lua:561
 playerLevel = 70
 Version = "10.2.5.106"
 EditConsumable = <function> defined @Buffet/Buffet.lua:753
 SlashHandler = <function> defined @Buffet/Buffet.lua:824
 availableItems = <table> {
 }
 ResetBest = <function> defined @Buffet/Buffet.lua:238
 scanning = true
}
delayedScanRequired = false
itemIds = <table> {
 6256 = 1
 199719 = 1
 6948 = 1
 199528 = 1
 199526 = 1
 40772 = 1
 199521 = 1
 3530 = 20
 199636 = 1
 199524 = 1
 33447 = 20
 27854 = 20
 33448 = 20
 199724 = 1
 28399 = 20
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 6256 = 1
 199719 = 1
 6948 = 1
 199528 = 1
 199526 = 1
 40772 = 1
 199521 = 1
 3530 = 20
 199636 = 1
 199524 = 1
 33447 = 20
 27854 = 20
 33448 = 20
 199724 = 1
 28399 = 20
}
(for control) = 6256
k = 6256
v = 1
itemId = 6256
itemCount = 1
itemName = "Fishing Pole"
itemLink = "|cffffffff|Hitem:6256::::::::70:::::::::|h[Fishing Pole]|h|r"
_ = 1
itemLevel = 1
itemMinLevel = 0
_ = "Weapon"
_ = "Fishing Poles"
_ = 1
_ = "INVTYPE_2HWEAPON"
_ = 132932
_ = 4
itemClassId = 2
itemSubClassId = 20
(*temporary) = nil
(*temporary) = 2
(*temporary) = 20
(*temporary) = "attempt to call field 'IsValidItemClasses' (a nil value)"
Core = <table> {
 scanAttempt = <table> {
 }
 bests = <table> {
 }
 OnTimerCallback = <function> defined @Buffet/Buffet.lua:266
 itemCache = <table> {
 }
 customMacros = <table> {
 }
 CompileSource = <function> defined @Buffet/Buffet.lua:543
 SetBest = <function> defined @Buffet/Buffet.lua:802
 Scan = <function> defined @Buffet/Buffet.lua:275
 RunChunk = <function> defined @Buffet/Buffet.lua:525
 EditDefault = <function> defined @Buffet/Buffet.lua:679
 EnableDelayedScan = <function> defined @Buffet/Buffet.lua:258
 EditFoodOnly = <function> defined @Buffet/Buffet.lua:726
 ResetAvailableItems = <function> defined @Buffet/Buffet.lua:244
 firstRun = true
 SetAvailable = <function> defined @Buffet/Buffet.lua:813
 ignoredItemCache = <table> {
 }
 AvailableItemsBeautifier = <function> defined @Buffet/Buffet.lua:603
 nextScan = 0
 db = <table> {
 }
 nextScanDelay = 1.200000
 playerMana = 3963
 BestsBeautifier = <function> defined @Buffet/Buffet.lua:583
 Edit = <function> defined @Buffet/Buffet.lua:661
 PrintItemData = <function> defined @Buffet/Buffet.lua:1004
 playerHealth = 7054
 QueueScan = <function> defined @Interf

**Comment by HgAlexx** [comment]
Hello,

Please try beta version 107 and report any issues.

Thank you.

**Comment by AutolycusWolf** [comment]
> Hello,
> 
> Please try beta version 107 and report any issues.
> 
> Thank you.

Beta 107 seems to be working with no issues up till now.
