### ISSUE TITLE
TOC Version

### ISSUE THREAD

**Issue by Talyrius** [HgAlexx/Buffet#7]
The TOC for the latest beta release of the classic version ([1.13.5.61_Classic-Beta](https://www.curseforge.com/wow/addons/buffet/files/3002309)) is using the retail game's version which is causing the Twitch app to download the incorrect release.

**Comment by HgAlexx** [comment]
Hello,
I forgot to change it before tagging the last release :)
I'll push a new beta tomorrow and it should fix this issue.

Thank you for your report!

**Comment by HgAlexx** [comment]
Oh btw, there no differences between version except for the toc version.
So it doesn't really matter ;)

**Comment by Talyrius** [comment]
I figured as much, but Classic players won't see the latest release.

**Comment by HgAlexx** [comment]
That's strange, it should see it as long as there is Classic in the name :(
Maybe they changed that. Anyway, should be fix tomorrow :)

**Comment by HgAlexx** [comment]
Hi again,
I've just though about it, but beta version do not show by default in the twitch client.
Might be why you don't see it.

**Comment by Talyrius** [comment]
I have the preferred release type set to Alpha for both, Classic and Retail.

**Classic:**
![image](https://user-images.githubusercontent.com/1068810/88634061-bcbf8400-d06a-11ea-90e7-38441f249c23.png)
![image](https://user-images.githubusercontent.com/1068810/88634365-22137500-d06b-11ea-999d-ea0cf4f5b40a.png)

**Retail:**
![image](https://user-images.githubusercontent.com/1068810/88634572-6737a700-d06b-11ea-9d24-172c24c44e2e.png)

**Comment by HgAlexx** [comment]
I've just push a new beta release for both retail and classic, with proper toc version, hope it works now!
