### ISSUE TITLE
Large value combo foods misreported as small.

### ISSUE THREAD

**Issue by Crelam** [HgAlexx/Buffet#75]
Large value consumables that restore health and mana are being misreported as small.  For example, Darkmoon Daggermaw (https://www.wowhead.com/item=124669) are reporting as health value: 3.1 and mana value: 4.2 instead of 3150000 and 4200000 respectively.

**Comment by HgAlexx** [comment]
Hello, please try version 119.

**Comment by Crelam** [comment]
Working as expected.  Thanks!
