### ISSUE TITLE
[Classic] Add Bottled Alterac Spring Water (19318) as a water (can be used anywhere)

### ISSUE THREAD

**Issue by skywardpixel** [HgAlexx/Buffet#77]
**Describe the bug**
Bottled Alterac Spring Waters are not picked up by the AutoMP macro.

**To Reproduce**
Steps to reproduce the behavior if applicable:

**Related Item**
https://www.wowhead.com/classic/item=19318/bottled-alterac-spring-water

**Language**
Please specify the language of your wow client:

**Comment by HgAlexx** [comment]
Hello,

This is a "well-fed" water which are ignored by default, but there is an option to include them if you want.

Is the item not picked up with the option enabled?

**Comment by skywardpixel** [comment]
Ah the item shows up after checking that option. Thank you!
