### ISSUE TITLE
Shadowlands support (SetBackdrop)

### ISSUE THREAD

**Issue by spiralofhope** [HgAlexx/Buffet#8]
When I view `Interface > Addons` I get an error:

For Config.lua 130:
https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes#backdrop-system-changes

**Comment by HgAlexx** [comment]
Hello,
I'll have a look at that as soon as possible.
Thanks.

**Comment by HgAlexx** [comment]
Hello,
This should be fix with last commit.

**Comment by spiralofhope** [comment]
Confirmed working; thanks!

**Comment by HgAlexx** [comment]
I'll try to do a proper release with weekend.
